config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home' => 'root#home'
  devise_for :users
  root"books#index"
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  get 'top' => 'root#top'
  get 'aho' => 'root#show'
  get "about" => "root#about"
  get "books" => "edit#destroy"
  get "books/:id/edit" => "books#edit", as: "books_edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
  	validates :title, presence: true
  	validates :opinion, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: { in: 2..20 }
  validates :opinion, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end
	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	def new
		@book = Book.new
    end
    def create
    	@book = Book.new(book_params)
    	@book.user_id = current_user.id
    	if @book.save
    	flash[:notice] = "successfully"
    	redirect_to book_path(@book.id)
    	else
    		@books = Book.all
    		render :index
        end
    end
    def index
    	@books = Book.all
    	@book = Book.new

    end
    def show
    	@book = Book.find(params[:id])
    	@bookn = Book.new
    	@books = Book.all
    end
    def destroy
    	@book = Book.find(params[:id])
    	@book.destroy
    	redirect_to books_path
    end
    def update

    end
    def edit
        @book = Book.find(params[:id])
    end


private
    def book_params
        params.require(:book).permit(:title, :opinion,)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
skip_before_action :authenticate_user!, only: [:home, :about]
	def top
	end
	def homes
	end
	def show
	end
	def about
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book =  Book.new
  end
  def edit
  	@user = User.find(params[:id])
  end
  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  end
  def index
  	@user = current_user
    @book = Book.new
    @users = User.all
  end
end


private
def user_params
    params.require(:user).permit(:name, :profile_image)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/home.html.erb
hoge

app/views/books/index.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
        <%= render "temple/list",book: @book,user: current_user %>

<%# end %>
      <div class="col-xs-9 ">

        <table class="table table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
           <% @books.each do |book| %>
              <tbody>
                <tr>
                  <td><%= attachment_image_tag book.user, :profile_image %></td>
                  <td>
                    <%= link_to book_path(book.id) do %>
                      <%= book.title %>
                    <% end %>
                  </td>
                  <td><%= book.opinion %></td>
                </tr>
              </tbody>
           <% end %>
        </table>
      </div>
    </div>
    </div>
  </div>
</section>ß

app/views/books/new.html.erb
<!-- <form> -->
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= render "temple/list",book: @book,user: current_user %>
  <div class="row">
    <div class="col-sm-12">
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group has-icon">
        <label class="control-label sr-only">ショップ名</label>
        <%= f.text_field :title, placeholder:"ショップ名" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :opinion, rows:"3", placeholder:"コメントここに" %>
    </div>
  </div>
  <hr>
  <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>
<!-- </form> -->

app/views/books/show.html.erb
        <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
  <div class="container">
  	<div class="row">
  	<%= render "temple/list",book: @bookn,user: current_user %>
  	 <div class="col-xs-9 ">
          <table class="table table-striped">
          	<thead>
          		<tr>
          			<th>Book detail</th>
          		</tr>
          	</thead>
          	<tbody>
          		<tr>
                  <td><%= attachment_image_tag @book.user, :profile_image %></td>
                  <td><%= link_to book_path(@book.id) do %>
                      <%= @book.title %>
                      <% end %>
                  </td>
                  <td><%= @book.opinion %></td>
                  <td><%# link_to book %></td>
                   <% if @book.user == current_user %>

                  <td>
                    <%= link_to "Edit", edit_book_path(@book.id),class: "btn btn-success" %>
                  </td>
                 <td>
                  <%= link_to "Destroy", book_path(@book.id), method: :delete %>
                 </td>
     <% end %>
    </li></td>
          		</tr>
          	</tbody>
          </table>
	  </div>
	 </div>
  </div>
  <br>

 <li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse">
       <div class="container">
          <div class="container-fluid">
              <div class="navbar-header">
                <span>Bookers</span>
              </div>
              <div id="slidemenu">
                <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
                  <% if user_signed_in? %>
                    <li class="">
                      <%= link_to "Home", user_path(current_user.id),class: "glyphicon glyphicon-home" %>
                    </li>
                    <li class="">
                      <%= link_to 'Users', users_path,class: "glyphicon glyphicon-user" %>
                    </li>
                    <li class="">
                      <%= link_to 'Books', books_path,class: "glyphicon glyphicon-book" %>
                    </li>
                    <li class="">
                    </li>
                    <li class="">
                      <%= link_to "Logout", destroy_user_session_path,class: "glyphicon glyphicon-share", method: :delete %>
                    </li>
                  <% else %>
                    <li class="">
                      <%= link_to "Home", home_path,class: "glyphicon glyphicon-home" %>
                    </li>
                    <li class="">
                      <%= link_to "About", about_path,class: "glyphicon glyphicon-link" %>
                    </li>
                    <li class="">
                      <%= link_to "sign up", new_user_registration_path,class: "glyphicon glyphicon-edit" %>
                    </li>
                    <li class="">
                      <%= link_to "login", new_user_session_path,class: "glyphicon glyphicon-log-in" %>
                    </li>
                  <% end %>
                </ul>
               </div>
             </div>
        </div>
      </div>
    </nav>
   <%= yield %>
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-9">
      <span>CopyRight Infratop.inc</span>
    </div>
  </div>
</div>
  </body>
</html>

app/views/root/about.html.erb
<div class="container">
	<h1>Welcoe to<span class="glyphicon glyphicon-book"></span>
	<strong>Bookers!</strong></h1>

app/views/root/home.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<h1>Welcome to<br><span class="glyphicon glyphicon-book"></span><strong>Bookers!</strong></h1>
		<p>"In"<span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>","
		</p>
		<p>you can share and exchange your opinions , inpressions , and emotions</p>
		<p>about various books!</p>
		<div class="btn-wrapper">
		</div>
		<div class="row">
			<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>
		</div>
		<div  class="row">
			<%= link_to "Sign Up",new_user_registration_path,class: "btn btn-success col-xs-10 col-xs-offset-1" %>
		</div>
     </div>
 </div>

app/views/root/show.html.erb
aaaaaaaaaaa

app/views/root/top.html.erb
top

app/views/temple/_list.html.erb
		<div class="col-xs-3">
			<%= form_for(book) do |f| %>
			<% if book.errors.any? %>
        <%= book.errors.count %>errors prohibited this obj from being saved:
        <% book.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>
			<h2>User info</h2>
				<%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: 'jpeg', fallback: "no_image.jpg",size: "100x100" %>

				<table class="table">
					<thead>
						<tr>
							<th>name</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>introduction</td>
						</tr>
					</tbody>
				</table>
			<div>
			<%= link_to "", edit_user_path(user.id), class: "glyphicon glyphicon-wrench btn btn-default col-xs-12" %>
			</div>
			<h2>New book</h2>
			<h5>Title</h5>
			<%= f.text_field :title, class: "col-xs-12" %>
			<h5>Opinion</h5>
			<%= f.text_field :opinion,class: "col-xs-12" %>
			<br>
			<br>
			<%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
			<% end %>
		</div>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_for (@user) do |f| %>
  <h4>Name</h4>
  <%= f.text_field :name %>
  <h4>Image</h4>
  <%= f.attachment_field :profile_image %>
  <label>Introduction</label>
  <%= f.text_area :introduction %>
  <br>
  <%= f.submit "Updaye User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<%= render "temple/list",book: @book,user: current_user %>

		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |u| %>
					<tr>
						<td><%= attachment_image_tag u, :profile_image, :fill, 100,100, format: 'jpeg', fallback: "no_image.jpg",size: "100x100" %></td>
						<td><%= u.name %></td>
						<td><%= link_to "show", user_path(u.id) %></td>
					</tr>

					<% end %>
				</tbody>
			</table>
		</div>

	</div>
</div>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= render "temple/list",book: @book,user: current_user %>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover tasble-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |b| %>
        <tr>
          <td><%= attachment_image_tag b.user, :profile_image, :fill, 100,100, format: 'jpeg', fallback: "no_image.jpg",size: "100x100" %></td>
          <td><%= link_to b.title, book_path(b.id) %></td>
          <td><%= b.opinion %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>s